// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_params
List test_params(int days, unsigned long pop_size, int sociability, double contagiousness, double mortality_rate, double resistance, int disease_length, int incubation_period, int latent_period);
RcppExport SEXP _Rpandemic_test_params(SEXP daysSEXP, SEXP pop_sizeSEXP, SEXP sociabilitySEXP, SEXP contagiousnessSEXP, SEXP mortality_rateSEXP, SEXP resistanceSEXP, SEXP disease_lengthSEXP, SEXP incubation_periodSEXP, SEXP latent_periodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type days(daysSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type pop_size(pop_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type sociability(sociabilitySEXP);
    Rcpp::traits::input_parameter< double >::type contagiousness(contagiousnessSEXP);
    Rcpp::traits::input_parameter< double >::type mortality_rate(mortality_rateSEXP);
    Rcpp::traits::input_parameter< double >::type resistance(resistanceSEXP);
    Rcpp::traits::input_parameter< int >::type disease_length(disease_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type incubation_period(incubation_periodSEXP);
    Rcpp::traits::input_parameter< int >::type latent_period(latent_periodSEXP);
    rcpp_result_gen = Rcpp::wrap(test_params(days, pop_size, sociability, contagiousness, mortality_rate, resistance, disease_length, incubation_period, latent_period));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rpandemic_test_params", (DL_FUNC) &_Rpandemic_test_params, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rpandemic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
