# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_params <- function(days, pop_size, sociability, resistance, virusParams) {
    .Call('_Rpandemic_test_params', PACKAGE = 'Rpandemic', days, pop_size, sociability, resistance, virusParams)
}

try_lockdown <- function(days, popParams, virusParams, sensitivity, aggressiveness) {
    .Call('_Rpandemic_try_lockdown', PACKAGE = 'Rpandemic', days, popParams, virusParams, sensitivity, aggressiveness)
}

generate_world <- function(popParams, virusParams) {
    .Call('_Rpandemic_generate_world', PACKAGE = 'Rpandemic', popParams, virusParams)
}

increment_days <- function(start_date, end_date, population) {
    .Call('_Rpandemic_increment_days', PACKAGE = 'Rpandemic', start_date, end_date, population)
}

