# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_params <- function(days, pop_size, sociability, contagiousness, mortality_rate, resistance, disease_length, incubation_period, latent_period) {
    .Call('_Rpandemic_test_params', PACKAGE = 'Rpandemic', days, pop_size, sociability, contagiousness, mortality_rate, resistance, disease_length, incubation_period, latent_period)
}

